### PR TITLE
extend() using prototype

### PR DESCRIPTION
**Pull request by anotherpit**
Implements #151

----

And a little bonus. To avoid circular dependencies I had to introduce a `Form.makeField()` factory method. Cool side effect is that now you provide custom class for fields. E.g.

```js

class MyField extends Field {
   // Extend base Field class with some logic specific to your app
}

class MyForm extends Form {
  // ...
  makeField(key, path, data, state, props, update, $form) {    
    return new MyField(key, path, data, state, props, update, $form);
  }
}
```

Should work with nested forms/fields as well. I cannot come up with any plausible use-case for this right now (that's why I didn't cover it with any tests), but I believe there are some.

### CODE REVIEW

**Comment by foxhound87** [comment]
@anotherpit cool PR! thank you so much!

**Comment by foxhound87** [comment]
I will document the `makeField` method

**Comment by foxhound87** [comment]
I made a refactoring and now we can write `makeField` like this: 

```
 makeField(data) {
    return new Field(data);
 }
```

so should be easier for end users to extend the `Field` class.
I will write tests and publish a new version asap.

**Comment by anotherpit** [comment]
@foxhound87 Actually, I doubt that such a controversial improvement was worth those drastic API changes. But what has been done cannot be undone, so I just ask you to mark new release as 1.15.0, not 1.14.6, so that guys having `"mobx-react-form": "^1.14.4"` in their `package.json` don't get too surprised during next deployment or `npm install`.

**Comment by foxhound87** [comment]
I will add this exports into index:

```
export default Form;
export { Form, Field };
```

so this will not break the existing api.
anyway I will release it as `1.15.0`

**Comment by foxhound87** [comment]
Extend Field Documentation: 
https://foxhound87.github.io/mobx-react-form/docs/api-reference/extend.html

**Pull request merged**
