### PR TITLE
fix: Form.makeField() signature

### PR DESCRIPTION
**Pull request by anotherpit**

### CODE REVIEW

**Comment by foxhound87** [comment]
my idea was to decrease the arguments passed and make the extended field implementation easier and cleaner. 

we can do something like:

```
  makeField(data) {
    return new NewField(data, this);
  }
```

and you can still use object destructuring on the first argument anyway

**Comment by foxhound87** [comment]
I think the form as second argument should be better, so we can remove it after without breaking the api if we found a better solution.

**Comment by anotherpit** [comment]
But why would we want to? Orphan field without parent form doesn't make any sense, does it?

**Comment by anotherpit** [comment]
Yeah, you are right, one day we may invent something like detached fields
```js
const field = new Field({...});
// ... prepare field somehow
field.appendTo(form);
```

**Comment by foxhound87** [comment]
Done here: https://github.com/foxhound87/mobx-react-form/commit/5edbd95f62e235952ffdbc48c10c2139ace7a3ad

thank you anyway 👍

**Pull request closed without merging**
