### PR TITLE
Fix Nested Fields Methods docs

### PR DESCRIPTION
**Pull request by anotherpit**
Remove mentions of non-existent methods

### CODE REVIEW

**Comment by foxhound87** [comment]
This doc file is correct as it is.

Since you can use those methods both on form or fields to get nested fields data.

For example:

``` javascript
const fields = [
  'files',
  'files[]',
];

...
form.update({ files: ['file1', 'file2'] });

console.log(form.values()); 
// => { files: [ 'file1', 'file2' ] }

console.log(form.$('files').values()); 
// => [ 'file1', 'file2' ]

```

**Comment by anotherpit** [comment]
Sorry, my bad.

**Comment by foxhound87** [comment]
Maybe the title **Nested Fields Methods** is a bit confusing.

Thank you for your contribution anyway :)

**Comment by foxhound87** [comment]
Some examples for this case here:  https://github.com/foxhound87/mobx-react-form/issues/148

**Pull request closed without merging**
