### PR TITLE
Add support for v5 proposals

### PR DESCRIPTION
**Pull request by patrykkopycinski**

### CODE REVIEW

**Comment by foxhound87** [comment]
Thanks for contributing!

**Comment by patrykkopycinski** [comment]
@foxhound87 could you do a release? ;)

**Comment by foxhound87** [comment]
@patrykkopycinski  of course!

**Comment by foxhound87** [comment]
@patrykkopycinski v.1.4.0 ready!

**Comment by patrykkopycinski** [comment]
Thanks! Did you work with `constant` keyword? I have an issue with checking if both inputs have the same value
here is the code: http://www.webpackbin.com/NJQPmYNPW

**Comment by patrykkopycinski** [comment]
And also it'd be great if you could update Demo link, because in `form.js` it should be `export default new Form({ fields, schema });` instead of `export default new Form(fields, schema);`

**Comment by foxhound87** [comment]
Updated the demo with new version and new constructor style.
To do a comparative validation you can see this: https://github.com/json-schema/json-schema/wiki/%24data-%28v5-proposal%29

**Comment by foxhound87** [comment]
Or you can use a custom validator passing a `validate` function to a field like this:

``` javascript
const fields = {
  username: {
    label: 'Username',
    validate: (field, fields) => {
      // field.value; // get current field value
      // fields.anotherfield.value; // get anotherfield value
      // do some validation stuff
      // return true / false
    },
  },
}
```

**Comment by patrykkopycinski** [comment]
i can't see updated demo. Could you provide some working example with `validate`? Because it doesn't work to me

**Comment by foxhound87** [comment]
Sorry, every time I updated the demo it generated another url: http://www.webpackbin.com/EyE8JnEDW

I'll change it on the readme too.

I didn't tested the validator function yet using simultaneously a json schema.
So I have to fix this on the next release asap.

**Comment by patrykkopycinski** [comment]
no problem, could you test `message` too? because it seems i can't provide custom error message

**Comment by foxhound87** [comment]
@patrykkopycinski messages and custom function fixed in ea163ba0

You can find a better example now on the doc!

**Comment by patrykkopycinski** [comment]
wow 🚀  

i can't wait to test it! Thanks @foxhound87 !

**Comment by foxhound87** [comment]
@patrykkopycinski  Let me know your feedbacks! I'm not so happy for the current style of showing errors, because every message is shown on every onChange event of any field. This for supporting the validation that depends on others field's values. I have to design a mechanism to show all messages only on submit button.

**Pull request merged**
