### PR TITLE
Typescript typings

### PR DESCRIPTION
**Pull request by anotherpit**
Addresses #150

- [x] Added Typescript typings
- [x] Added some NPM tasks to automate Typescript things
- [x] Introduced testing approach for typings
- [ ] Cover `Field` with tests
- [ ] Use typings in external projects for a while (a.k.a. field testing)
- [ ] Maybe, add protected methods to typings so that, for example, people extending `Form` class don't have issues when calling `super` methods. This can be a little bit tricky as the original JS code don't make any difference between public/protected/private methods (e.g. no `_` prefixes, no difference in docs, etc.)

### CODE REVIEW

**Comment by foxhound87** [comment]
Can I merge this or you want to check the latest 3 tasks?

**Comment by anotherpit** [comment]
Let's merge so that other guys can contribute to the branch, because it seems to me I'm not going to have enough time to finish it in the near future.

**Comment by anotherpit** [comment]
@foxhound87, also how about referring this branch (and need of contributors for it) in the README file on the `master` branch or in docs?

**Comment by Strate** [comment]
Any way to check this branch out to test typings?

**Comment by foxhound87** [comment]
This branch should be updated first

**Comment by anotherpit** [comment]
@Strate 

Well, it's just a regular branch, so you can check it out as any other branch of any other repo. You can `git clone` this project and check out `typescript` branch. Or if you use this library with `npm` you can specify `mobx-react-form: foxhound/mobx-react-form#typescript` in your `package.json`. 

Anyway, the branch is outdated and, as @foxhound87 mentioned, needs an update. There's no chance I'll be able to maintain the branch in the nearest future so contribution is very anticipated. But honestly I don't see how one can keep this branch up to date with the `master` branch given how often [new releases](https://github.com/foxhound87/mobx-react-form/releases) are published (including those that change API). The only way I can imagine is to rewrite the whole library to Typescript, but I don't believe this would ever happen.

**Pull request merged**
