### PR TITLE
fix issue #495

### PR DESCRIPTION
**Pull request by riceyeh**

### CODE REVIEW

**Comment by foxhound87** [comment]
Thank you for the PR.
maybe we should use `field.clear()` instead of `field.set('')` to handle other types?

**Comment by riceyeh** [comment]
@foxhound87,
  Yes, field.clear() is better. Could you merge this pull request and replace the statement field.set('') to this.clear(). I tried it. It pass the tests. Or you have other better solution for issue #495?

**Comment by foxhound87** [comment]
Yes. I'll take care of it.
Your solution seems good.

**Pull request merged**
