### PR TITLE
[WIP] Conversion to Typescript

### PR DESCRIPTION
**Pull request by danielkcz**
After finding stale #150 and obsolete #166 I've decided to give it an attempt. I agree with @devdoomari that maintaining `.d.ts` files is an extra hassle. So I simply renamed all files to `*.ts` and with help of compiler fixed syntax error issues.

However, there is quite a lot of errors coming from bad types and I think it would require a non-trivial level of refactoring. As I am not even using project yet, I am pretty much unfamiliar with it. Let's consider this as another attempt and perhaps with help of others it can be finished.

I also temporarily disabled precommit hook which is obviously failing now.

### CODE REVIEW

**Comment by foxhound87** [comment]
@FredyC thank you for your contribution, what issues have you encountered?
Let me know if I can help you to finish this update. 
I'm available to chat, you can ping me on twitter PM eventually.

**Comment by ekozhura** [comment]
@FredyC @foxhound87 do you need any help with the migration to typescript?

**Comment by foxhound87** [comment]
@ekozhura yes please, any help would be highly appreciated, thank you.

**Comment by ekozhura** [comment]
@FredyC did you manage to fix compilation errors?

**Comment by danielkcz** [comment]
@ekozhura I haven't dive into that yet. There is too much of it and I am still pretty much getting know this lib. For now, I am writing some temporary types to pass through the compiler and to improve my understanding how to do these. Once I get past some more complex forms, I might reconsider this approach :)

Here is what I got so far, it's quite messy, but might help someone :)

```typescript
declare module 'mobx-react-form' {
  export default MRF.MobxReactForm
}

type Dictionary<T> = { [key: string]: T }

declare namespace MRF {
  class MobxReactForm {
    constructor(options: MRF.Options, settings?: MRF.Settings)
    isValid: boolean
    get(field: string): string
    set(obj: Dictionary<string>): void
    $(selector: string): Field
    onSubmit(): void
    init(obj: Dictionary<string>): void
    validate(): void
    values(): Dictionary<string>
    submit<T>(handlers: { onSuccess?: Handler; onError?: Handler }): Promise<T>
    errors(): Dictionary<string>
    select(path: string): Field
    submitting: boolean
  }

  type Handler = (form: MobxReactForm) => void | Promise<any>

  interface Field extends FieldSpec {
    bind(): FieldSpec
  }

  interface FieldSpec {
    name?: string
    value?: string
    label?: string
    placeholder?: string
    rules?: string
  }

  type FieldsDefinition = string[] | Dictionary<string | FieldSpec>

  interface Options {
    fields?: FieldsDefinition
    values?: Dictionary<string>
  }

  interface Settings {
    plugins?: {
      dvr: any
    }
    hooks?: {
      onSuccess(form: MobxReactForm): void
    }
    options?: {}
  }
}
```

**Comment by abelkbil** [comment]
@foxhound87 , @FredyC Thanks for the conversion . Right now i am not using this, My application is in typescript. Can I use the current version with typescript.

**Comment by wwahammy** [comment]
What is necessary for this to be merged? In the last two days, I've done this on my own (because I didnt' see this is there). Would it be acceptable to merge a minimally typesafe version (most types are just any) in typescript as a starting point? The types are kind of complex and I worry that waiting for a perfect version will make it an impossible task.

**Comment by foxhound87** [comment]
@ericschultz do you think you can pull the latest commits/updates from the master branch?

**Comment by wwahammy** [comment]
I can in the next few days, I'm only behind master by a few commits.

**Comment by foxhound87** [comment]
the previous version of the `typescript` branch is now on `typescript-old`:
https://github.com/foxhound87/mobx-react-form/tree/typescript-old

**Comment by foxhound87** [comment]
PR moved on #442

**Pull request closed without merging**
