### PR TITLE
Fix Form.validate(field)

### PR DESCRIPTION
**Pull request by anotherpit**
According to [docs](https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-methods.html) `.validate(field)` was supposed to be a valid method call, but it actually didn't work: the returned Promise never got resolved as it referred `$field` variable which was set to null if you didn't explicitly pass field instance to the method. This PR fixes the issue. Tests provided.

P.S. There are also some minor improvements, e.g. fixed typos, etc. Well, I wouldn't mind move them to their own separate PR if they frustrate you as a part of this one.

P.P.S. Happy to see lint and tests tightly bound to Git hooks.

### CODE REVIEW

**Comment by foxhound87** [comment]
@anotherpit thank you for this pull request.

About the `lint` script, I use to lint the `demo` directory which is sym-linked to the project.

**Comment by anotherpit** [comment]
@foxhound87 Yeah, I see. But since you moved demo project to its own repo or somewhere else, linting of `demo` should be also moved there. Otherwise, contributors are unable to commit: commit hook runs `lint` task, and `lint` task needs `demo` folder to exists.

**Comment by foxhound87** [comment]
@anotherpit I don't get any error on `npm run lint` if the `demo` dir doesn't exist.

**Comment by anotherpit** [comment]
I don't get errors when either both symlink and folder exist, or they both don't exist. When the symlink is in the project, and there's no `demo` folder I get the following on Mac OS:

``` bash
npm run lint

> mobx-react-form@0.0.0-semantically-released lint /Users/Pit/Projects/mobx-react-form
> eslint . demo --ext .jsx,.js --ignore-path .gitignore

ENOENT: no such file or directory, open '/Users/Pit/Projects/mobx-react-form/demo'
Error: ENOENT: no such file or directory, open '/Users/Pit/Projects/mobx-react-form/demo'
```

**Pull request merged**
