### PR TITLE
Add ability to manual submit from form object interface

### PR DESCRIPTION
**Pull request by volodymyr-xn**

### CODE REVIEW

**Comment by foxhound87** [comment]
I think this PR should be ok, why you closed it?

**Comment by volodymyr-xn** [comment]
Sorry, i had some troubles with Github api. 

I have moved up this function and redefined it as class method. 
Should i add this method in Form object docs?

**Comment by foxhound87** [comment]
I didn't noticed the codecov checks from the smartphone, we should add tests.

**Comment by volodymyr-xn** [comment]
Alright, i will add some tests for it.

**Comment by volodymyr-xn** [comment]
I can add tests for onSuccess and onError callbacks with "submit()" method test.
I could add them for two cases: 
1. Inline callbacks, that are passed in Form object constructor.
2. Callbacks that are defined as class methods.

**Comment by foxhound87** [comment]
Thank you!

**Pull request merged**
