### PR TITLE
update: mobx4 support

### PR DESCRIPTION
**Pull request by SDSLeon**
#391 @foxhound87

### CODE REVIEW

**Comment by vwong** [comment]
I noticed that care was taken to ensure that this library works with mobx2 and mobx3.  These changes you're proposing would break that backward compatibility.

@foxhound87 What's the appetite for maintaining compatibility across 3 different versions of mobx?  Surely if we aim for mobx4 only, we can cleanup some of the code too?

**Comment by foxhound87** [comment]
We can have the backward compatibility with older mobx version.
I will release it asap.

**Comment by vwong** [comment]
I'd be happy with a major version bump and only support the latest mobx in that, but if you can maintain compatibility across 3 different versions of mobx, that'd be good too. Looking forward to your release. Great work!

**Comment by SDSLeon** [comment]
Added backward compatibility for older mobx versions. Also run tests for 2 versions of mobx (3 and latest/4);

**Comment by foxhound87** [comment]
@SDSLeon great PR! Thank you!

**Pull request merged**
